
-- 테이블명 (엔티티명) : TWAA0001M00 (TWAA_노드기본) [MT_NODES]
CREATE TABLE TWAA0001M00 (
    MNG_DOM_NODE_ID NUMBER NOT NULL
    , MNG_DOM_NODE_NM VARCHAR2(20) NOT NULL
    , MNG_DOM_NODE_HST_IP VARCHAR2(32) NOT NULL
    , MNG_DOM_NODE_HST_PORT_NO VARCHAR2(5) NOT NULL
    , MNG_DOM_NODE_STAT_TYP_CODE VARCHAR2(1) NOT NULL
    , REG_USER_ID VARCHAR2(12) NOT NULL
    , REG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_ID VARCHAR2(12) NOT NULL
    , CHG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_IP VARCHAR2(32) NOT NULL
    , CHG_GBL_ID VARCHAR2(34) NOT NULL
) ;

CREATE UNIQUE INDEX TWAA0001M00_PK ON TWAA0001M00 (MNG_DOM_NODE_ID) ;
ALTER TABLE TWAA0001M00 ADD CONSTRAINT TWAA0001M00_PK PRIMARY KEY (MNG_DOM_NODE_ID) USING INDEX TWAA0001M00_PK;
COMMENT ON COLUMN TWAA0001M00.MNG_DOM_NODE_ID IS '관리영역노드ID';
COMMENT ON COLUMN TWAA0001M00.MNG_DOM_NODE_NM IS '관리영역노드명';
COMMENT ON COLUMN TWAA0001M00.MNG_DOM_NODE_HST_IP IS '관리영역노드호스트IP';
COMMENT ON COLUMN TWAA0001M00.MNG_DOM_NODE_HST_PORT_NO IS '관리영역노드호스트포트번호';
COMMENT ON COLUMN TWAA0001M00.MNG_DOM_NODE_STAT_TYP_CODE IS '관리영역노드상태유형코드';
COMMENT ON COLUMN TWAA0001M00.REG_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TWAA0001M00.REG_DDTS IS '등록상세일시TS';
COMMENT ON COLUMN TWAA0001M00.CHG_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN TWAA0001M00.CHG_DDTS IS '변경상세일시TS';
COMMENT ON COLUMN TWAA0001M00.CHG_USER_IP IS '변경사용자IP';
COMMENT ON COLUMN TWAA0001M00.CHG_GBL_ID IS '변경글로벌ID';
COMMENT ON TABLE TWAA0001M00 IS 'TWAA_노드기본';

-- 테이블명 (엔티티명) : TWAA0002M00 (TWAA_노드태그맵핑기본) [MT_NODE_TAG_MEMBERS]
CREATE TABLE TWAA0002M00 (
    MNG_DOM_NODE_TAG_MPG_ID NUMBER NOT NULL
    , MPG_MNG_DOM_TAG_ID NUMBER
    , MPG_MNG_DOM_NODE_ID NUMBER
    , REG_USER_ID VARCHAR2(12) NOT NULL
    , REG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_ID VARCHAR2(12) NOT NULL
    , CHG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_IP VARCHAR2(32) NOT NULL
    , CHG_GBL_ID VARCHAR2(34) NOT NULL
) ;
CREATE UNIQUE INDEX TWAA0002M00_PK ON TWAA0002M00 (MNG_DOM_NODE_TAG_MPG_ID) ;
ALTER TABLE TWAA0002M00 ADD CONSTRAINT TWAA0002M00_PK PRIMARY KEY (MNG_DOM_NODE_TAG_MPG_ID) USING INDEX TWAA0002M00_PK;
COMMENT ON COLUMN TWAA0002M00.MNG_DOM_NODE_TAG_MPG_ID IS '관리영역노드태그맵핑ID';
COMMENT ON COLUMN TWAA0002M00.MPG_MNG_DOM_TAG_ID IS '맵핑관리영역태그ID';
COMMENT ON COLUMN TWAA0002M00.MPG_MNG_DOM_NODE_ID IS '맵핑관리영역노드ID';
COMMENT ON COLUMN TWAA0002M00.REG_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TWAA0002M00.REG_DDTS IS '등록상세일시TS';
COMMENT ON COLUMN TWAA0002M00.CHG_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN TWAA0002M00.CHG_DDTS IS '변경상세일시TS';
COMMENT ON COLUMN TWAA0002M00.CHG_USER_IP IS '변경사용자IP';
COMMENT ON COLUMN TWAA0002M00.CHG_GBL_ID IS '변경글로벌ID';
COMMENT ON TABLE TWAA0002M00 IS 'TWAA_노드태그맵핑기본';

-- 테이블명 (엔티티명) : TWAA0003M00 (TWAA_태그기본) [MT_TAGS]
CREATE TABLE TWAA0003M00 (
    MNG_DOM_TAG_ID NUMBER NOT NULL
    , MNG_DOM_TAG_NM VARCHAR2(20)
    , REG_USER_ID VARCHAR2(12) NOT NULL
    , REG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_ID VARCHAR2(12) NOT NULL
    , CHG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_IP VARCHAR2(32) NOT NULL
    , CHG_GBL_ID VARCHAR2(34) NOT NULL
) ;

CREATE UNIQUE INDEX TWAA0003M00_PK ON TWAA0003M00 (MNG_DOM_TAG_ID) ;
ALTER TABLE TWAA0003M00 ADD CONSTRAINT TWAA0003M00_PK PRIMARY KEY (MNG_DOM_TAG_ID) USING INDEX TWAA0003M00_PK;
COMMENT ON COLUMN TWAA0003M00.MNG_DOM_TAG_ID IS '관리영역태그ID';
COMMENT ON COLUMN TWAA0003M00.MNG_DOM_TAG_NM IS '관리영역태그명';
COMMENT ON COLUMN TWAA0003M00.REG_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TWAA0003M00.REG_DDTS IS '등록상세일시TS';
COMMENT ON COLUMN TWAA0003M00.CHG_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN TWAA0003M00.CHG_DDTS IS '변경상세일시TS';
COMMENT ON COLUMN TWAA0003M00.CHG_USER_IP IS '변경사용자IP';
COMMENT ON COLUMN TWAA0003M00.CHG_GBL_ID IS '변경글로벌ID';
COMMENT ON TABLE TWAA0003M00 IS 'TWAA_태그기본';

-- 테이블명 (엔티티명) : TWAA0004M00 (TWAA_노드그룹기본) [MT_NODE_GROUPS]
CREATE TABLE TWAA0004M00 (
    MNG_DOM_NODE_GRP_ID NUMBER NOT NULL
    , SNET_MNG_NODE_GRP_NM VARCHAR2(20) NOT NULL
    , MNG_DOM_NODE_GRP_DES_CNTT VARCHAR2(1000) NOT NULL
    , REG_USER_ID VARCHAR2(12) NOT NULL
    , REG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_ID VARCHAR2(12) NOT NULL
    , CHG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_IP VARCHAR2(32) NOT NULL
    , CHG_GBL_ID VARCHAR2(34) NOT NULL
) ;

CREATE UNIQUE INDEX TWAA0004M00_PK ON TWAA0004M00 (MNG_DOM_NODE_GRP_ID) ;
ALTER TABLE TWAA0004M00 ADD CONSTRAINT TWAA0004M00_PK PRIMARY KEY (MNG_DOM_NODE_GRP_ID) USING INDEX TWAA0004M00_PK;
COMMENT ON COLUMN TWAA0004M00.MNG_DOM_NODE_GRP_ID IS '관리영역노드그룹ID';
COMMENT ON COLUMN TWAA0004M00.SNET_MNG_NODE_GRP_NM IS 'SNET관리노드그룹명';
COMMENT ON COLUMN TWAA0004M00.MNG_DOM_NODE_GRP_DES_CNTT IS '관리영역노드그룹설명내용';
COMMENT ON COLUMN TWAA0004M00.REG_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TWAA0004M00.REG_DDTS IS '등록상세일시TS';
COMMENT ON COLUMN TWAA0004M00.CHG_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN TWAA0004M00.CHG_DDTS IS '변경상세일시TS';
COMMENT ON COLUMN TWAA0004M00.CHG_USER_IP IS '변경사용자IP';
COMMENT ON COLUMN TWAA0004M00.CHG_GBL_ID IS '변경글로벌ID';
COMMENT ON TABLE TWAA0004M00 IS 'TWAA_노드그룹기본';

-- 테이블명 (엔티티명) : TWAA0005M00 (TWAA_노드그룹맵핑기본) [MT_NODE_GROUP_MEMBERS]
CREATE TABLE TWAA0005M00 (
    MNG_DOM_NODE_GRP_MMB_MPG_ID NUMBER NOT NULL
    , MPG_MNG_DOM_NODE_GRP_ID NUMBER
    , MPG_MNG_DOM_NODE_ID NUMBER
    , REG_USER_ID VARCHAR2(12) NOT NULL
    , REG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_ID VARCHAR2(12) NOT NULL
    , CHG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_IP VARCHAR2(32) NOT NULL
    , CHG_GBL_ID VARCHAR2(34) NOT NULL
) ;

CREATE UNIQUE INDEX TWAA0005M00_PK ON TWAA0005M00 (MNG_DOM_NODE_GRP_MMB_MPG_ID) ;
ALTER TABLE TWAA0005M00 ADD CONSTRAINT TWAA0005M00_PK PRIMARY KEY (MNG_DOM_NODE_GRP_MMB_MPG_ID) USING INDEX TWAA0005M00_PK;
COMMENT ON COLUMN TWAA0005M00.MNG_DOM_NODE_GRP_MMB_MPG_ID IS '관리영역노드그룹멤버맵핑ID';
COMMENT ON COLUMN TWAA0005M00.MPG_MNG_DOM_NODE_GRP_ID IS '맵핑관리영역노드그룹ID';
COMMENT ON COLUMN TWAA0005M00.MPG_MNG_DOM_NODE_ID IS '맵핑관리영역노드ID';
COMMENT ON COLUMN TWAA0005M00.REG_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TWAA0005M00.REG_DDTS IS '등록상세일시TS';
COMMENT ON COLUMN TWAA0005M00.CHG_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN TWAA0005M00.CHG_DDTS IS '변경상세일시TS';
COMMENT ON COLUMN TWAA0005M00.CHG_USER_IP IS '변경사용자IP';
COMMENT ON COLUMN TWAA0005M00.CHG_GBL_ID IS '변경글로벌ID';
COMMENT ON TABLE TWAA0005M00 IS 'TWAA_노드그룹맵핑기본';

-- 테이블명 (엔티티명) : TWAA0006M00 (TWAA_API파라미터기본) [MT_API_PARAMETERS]
CREATE TABLE TWAA0006M00 (
    MNG_DOM_API_INP_ID NUMBER NOT NULL
    , MNG_DOM_API_ID NUMBER
    , MNG_DOM_API_INP_NM VARCHAR2(20) NOT NULL
    , MNG_DOM_API_INP_TYP_NM VARCHAR2(20) NOT NULL
    , MNG_DOM_API_INP_ESN_YN VARCHAR2(1) NOT NULL
    , MNG_DOM_API_INP_DES_CNTT VARCHAR2(200)
    , REG_USER_ID VARCHAR2(12) NOT NULL
    , REG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_ID VARCHAR2(12) NOT NULL
    , CHG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_IP VARCHAR2(32) NOT NULL
    , CHG_GBL_ID VARCHAR2(34) NOT NULL
) ;
CREATE UNIQUE INDEX TWAA0006M00_PK ON TWAA0006M00 (MNG_DOM_API_INP_ID) ;
ALTER TABLE TWAA0006M00 ADD CONSTRAINT TWAA0006M00_PK PRIMARY KEY (MNG_DOM_API_INP_ID) USING INDEX TWAA0006M00_PK;
COMMENT ON COLUMN TWAA0006M00.MNG_DOM_API_INP_ID IS '관리영역API입력ID';
COMMENT ON COLUMN TWAA0006M00.MNG_DOM_API_ID IS '관리영역API_ID';
COMMENT ON COLUMN TWAA0006M00.MNG_DOM_API_INP_NM IS '관리영역API입력명';
COMMENT ON COLUMN TWAA0006M00.MNG_DOM_API_INP_TYP_NM IS '관리영역API입력타입명';
COMMENT ON COLUMN TWAA0006M00.MNG_DOM_API_INP_ESN_YN IS '관리영역API입력필수여부';
COMMENT ON COLUMN TWAA0006M00.MNG_DOM_API_INP_DES_CNTT IS '관리영역API입력설명내용';
COMMENT ON COLUMN TWAA0006M00.REG_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TWAA0006M00.REG_DDTS IS '등록상세일시TS';
COMMENT ON COLUMN TWAA0006M00.CHG_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN TWAA0006M00.CHG_DDTS IS '변경상세일시TS';
COMMENT ON COLUMN TWAA0006M00.CHG_USER_IP IS '변경사용자IP';
COMMENT ON COLUMN TWAA0006M00.CHG_GBL_ID IS '변경글로벌ID';
COMMENT ON TABLE TWAA0006M00 IS 'TWAA_API파라미터기본';

-- 테이블명 (엔티티명) : TWAA0007M00 (TWAA API기본) [MT_APIS]
CREATE TABLE TWAA0007M00 (
    MNG_DOM_API_ID NUMBER NOT NULL
    , MNG_DOM_API_NM VARCHAR2(40) NOT NULL
    , MNG_DOM_API_URL VARCHAR2(600) NOT NULL
    , HTTP_METHD_NM VARCHAR2(10) NOT NULL
    , REG_USER_ID VARCHAR2(12) NOT NULL
    , REG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_ID VARCHAR2(12) NOT NULL
    , CHG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_IP VARCHAR2(32) NOT NULL
    , CHG_GBL_ID VARCHAR2(34) NOT NULL
) ;
CREATE UNIQUE INDEX TWAA0007M00_PK ON TWAA0007M00 (MNG_DOM_API_ID) ;
ALTER TABLE TWAA0007M00 ADD CONSTRAINT TWAA0007M00_PK PRIMARY KEY (MNG_DOM_API_ID) USING INDEX TWAA0007M00_PK;
COMMENT ON COLUMN TWAA0007M00.MNG_DOM_API_ID IS '관리도메인API_ID';
COMMENT ON COLUMN TWAA0007M00.MNG_DOM_API_NM IS '관리도메인API명';
COMMENT ON COLUMN TWAA0007M00.MNG_DOM_API_URL IS '관리도메인APIURL';
COMMENT ON COLUMN TWAA0007M00.HTTP_METHD_NM IS 'HTTP메소드명';
COMMENT ON COLUMN TWAA0007M00.REG_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TWAA0007M00.REG_DDTS IS '등록상세일시TS';
COMMENT ON COLUMN TWAA0007M00.CHG_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN TWAA0007M00.CHG_DDTS IS '변경상세일시TS';
COMMENT ON COLUMN TWAA0007M00.CHG_USER_IP IS '변경사용자IP';
COMMENT ON COLUMN TWAA0007M00.CHG_GBL_ID IS '변경글로벌ID';
COMMENT ON TABLE TWAA0007M00 IS 'TWAA API기본';

-- 테이블명 (엔티티명) : TWAA0008M00 (TWAA API태그맵핑기본) [MT_API_TAG_MEMBERS]
CREATE TABLE TWAA0008M00 (
    MNG_DOM_API_TAG_MPG_ID NUMBER NOT NULL
    , MPG_MNG_DOM_TAG_ID NUMBER
    , MPG_MNG_DOM_API_ID NUMBER
    , REG_USER_ID VARCHAR2(12) NOT NULL
    , REG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_ID VARCHAR2(12) NOT NULL
    , CHG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_IP VARCHAR2(32) NOT NULL
    , CHG_GBL_ID VARCHAR2(34) NOT NULL
) ;
CREATE UNIQUE INDEX TWAA0008M00_PK ON TWAA0008M00 (MNG_DOM_API_TAG_MPG_ID) ;
ALTER TABLE TWAA0008M00 ADD CONSTRAINT TWAA0008M00_PK PRIMARY KEY (MNG_DOM_API_TAG_MPG_ID) USING INDEX TWAA0008M00_PK;
COMMENT ON COLUMN TWAA0008M00.MNG_DOM_API_TAG_MPG_ID IS '관리영역API태그맵핑ID';
COMMENT ON COLUMN TWAA0008M00.MPG_MNG_DOM_API_ID IS '맵핑관리영역API_ID';
COMMENT ON COLUMN TWAA0008M00.MPG_MNG_DOM_TAG_ID IS '맵핑관리영역태그ID';
COMMENT ON COLUMN TWAA0008M00.REG_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TWAA0008M00.REG_DDTS IS '등록상세일시TS';
COMMENT ON COLUMN TWAA0008M00.CHG_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN TWAA0008M00.CHG_DDTS IS '변경상세일시TS';
COMMENT ON COLUMN TWAA0008M00.CHG_USER_IP IS '변경사용자IP';
COMMENT ON COLUMN TWAA0008M00.CHG_GBL_ID IS '변경글로벌ID';
COMMENT ON TABLE TWAA0008M00 IS 'TWAA_API태그맵핑기본';



-- 테이블명 (엔티티명) : TWAA0009M00 (TWAA_합성테스트기본) [MT_SYNTHETIC_TESTS]
CREATE TABLE TWAA0009M00 (
    MNG_DOM_SYNT_TEST_ID NUMBER NOT NULL
    , MNG_DOM_SYNT_TEST_NM VARCHAR2(40) NOT NULL
    , MNG_DOM_SYNT_TEST_TRGT_TYP_NM VARCHAR2(20) NOT NULL
    , SYNT_TEST_MNG_DOM_EXE_TRG_ID NUMBER NOT NULL
    , SYNT_TEST_MNG_DOM_API_ID NUMBER NOT NULL
    , SYNT_TEST_EXE_INTV_TIME_HMS VARCHAR2(6)
    , MNG_DOM_SYNT_TEST_ALT_CRTL_MLSC NUMBER(18)
    , MNG_DOM_SYNT_TEST_VTLT_YN VARCHAR2(1) NOT NULL
    , REG_USER_ID VARCHAR2(12) NOT NULL
    , REG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_ID VARCHAR2(12) NOT NULL
    , CHG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_IP VARCHAR2(32) NOT NULL
    , CHG_GBL_ID VARCHAR2(34) NOT NULL
) ;

CREATE UNIQUE INDEX TWAA0009M00_PK ON TWAA0009M00 (MNG_DOM_SYNT_TEST_ID) ;
ALTER TABLE TWAA0009M00 ADD CONSTRAINT TWAA0009M00_PK PRIMARY KEY (MNG_DOM_SYNT_TEST_ID) USING INDEX TWAA0009M00_PK;
COMMENT ON COLUMN TWAA0009M00.MNG_DOM_SYNT_TEST_ID IS '관리영역합성테스트ID';
COMMENT ON COLUMN TWAA0009M00.MNG_DOM_SYNT_TEST_NM IS '관리영역합성테스트명';
COMMENT ON COLUMN TWAA0009M00.MNG_DOM_SYNT_TEST_TRGT_TYP_NM IS '관리영역합성테스트타겟유형명';
COMMENT ON COLUMN TWAA0009M00.SYNT_TEST_MNG_DOM_EXE_TRG_ID IS '합성테스트관리영역실행타겟ID';
COMMENT ON COLUMN TWAA0009M00.SYNT_TEST_MNG_DOM_API_ID IS '합성테스트관리영역API_ID';
COMMENT ON COLUMN TWAA0009M00.SYNT_TEST_EXE_INTV_TIME_HMS IS '합성테스트실행간격시간HMS';
COMMENT ON COLUMN TWAA0009M00.MNG_DOM_SYNT_TEST_ALT_CRTL_MLSC IS '관리영역합성테스트ALERT일임계밀리초';
COMMENT ON COLUMN TWAA0009M00.MNG_DOM_SYNT_TEST_VTLT_YN IS '관리영역합성테스트활성여부';
COMMENT ON COLUMN TWAA0009M00.REG_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TWAA0009M00.REG_DDTS IS '등록상세일시TS';
COMMENT ON COLUMN TWAA0009M00.CHG_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN TWAA0009M00.CHG_DDTS IS '변경상세일시TS';
COMMENT ON COLUMN TWAA0009M00.CHG_USER_IP IS '변경사용자IP';
COMMENT ON COLUMN TWAA0009M00.CHG_GBL_ID IS '변경글로벌ID';
COMMENT ON TABLE TWAA0009M00 IS 'TWAA_합성테스트기본';

-- 테이블명 (엔티티명) : TWAA0010M00 (TWAA_합성테스트태그맵핑기본) [MT_SYNTHETIC_TEST_TAG_MEMBERS]
CREATE TABLE TWAA0010M00 (
    MNG_DOM_SYNT_TEST_TAG_MPG_ID NUMBER NOT NULL
    , MPG_MNG_DOM_TAG_ID NUMBER
    , MPG_MNG_DOM_SYNT_TEST_ID NUMBER
	, REG_USER_ID VARCHAR2(12) NOT NULL
	, REG_DDTS TIMESTAMP NOT NULL
	, CHG_USER_ID VARCHAR2(12) NOT NULL
	, CHG_DDTS TIMESTAMP NOT NULL
	, CHG_USER_IP VARCHAR2(32) NOT NULL
	, CHG_GBL_ID VARCHAR2(34) NOT NULL
) ;

CREATE UNIQUE INDEX TWAA0010M00_PK ON TWAA0010M00 (MNG_DOM_SYNT_TEST_TAG_MPG_ID) ;
ALTER TABLE TWAA0010M00 ADD CONSTRAINT TWAA0010M00_PK PRIMARY KEY (MNG_DOM_SYNT_TEST_TAG_MPG_ID) USING INDEX TWAA0010M00_PK;
COMMENT ON COLUMN TWAA0010M00.MNG_DOM_SYNT_TEST_TAG_MPG_ID IS '관리영역심테스트태그맵핑ID';
COMMENT ON COLUMN TWAA0010M00.MPG_MNG_DOM_TAG_ID IS '맵핑관리영역태그ID';
COMMENT ON COLUMN TWAA0010M00.MPG_MNG_DOM_SYNT_TEST_ID IS '맵핑관리영역심성테스트ID';
COMMENT ON COLUMN TWAA0010M00.REG_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TWAA0010M00.REG_DDTS IS '등록상세일시TS';
COMMENT ON COLUMN TWAA0010M00.CHG_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN TWAA0010M00.CHG_DDTS IS '변경상세일시TS';
COMMENT ON COLUMN TWAA0010M00.CHG_USER_IP IS '변경사용자IP';
COMMENT ON COLUMN TWAA0010M00.CHG_GBL_ID IS '변경글로벌ID';
COMMENT ON TABLE TWAA0010M00 IS 'TWAA_합성테스트태그맵핑기본';

-- 테이블명 (엔티티명) : TWAA0011H00 (TWAA_합성테스트실행이력) [MT_SYNTHETIC_TEST_HISTORY]
CREATE TABLE TWAA0011H00 (
    MNG_DOM_SYNT_TEST_EXE_HIST_ID NUMBER NOT NULL
    , MNG_DOM_SYNT_TEST_ID NUMBER
    , MNG_DOM_NODE_ID NUMBER NOT NULL
    , MNG_DOM_SYNT_TEST_HTTP_RSP_CODE VARCHAR2(4)
    , MNG_DOM_SYNT_TEST_SCS_YN VARCHAR2(1)
    , MNG_DOM_SYNT_TEST_RSP_MLSC NUMBER(18)
    , MNG_DOM_SYNT_TEST_EXE_TM VARCHAR2(6)
    , MNG_DOM_SYNT_TEST_INP_CNTT VARCHAR2(4000)
    , MNG_DOM_SYNT_TEST_OPRT_CNTT VARCHAR2(4000)
    , REG_USER_ID VARCHAR2(12) NOT NULL
    , REG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_ID VARCHAR2(12) NOT NULL
    , CHG_DDTS TIMESTAMP NOT NULL
    , CHG_USER_IP VARCHAR2(32) NOT NULL
    , CHG_GBL_ID VARCHAR2(34) NOT NULL
) ;

CREATE UNIQUE INDEX TWAA0011H00_PK ON TWAA0011H00 (MNG_DOM_SYNT_TEST_EXE_HIST_ID) ;
ALTER TABLE TWAA0011H00 ADD CONSTRAINT TWAA0011H00_PK PRIMARY KEY (MNG_DOM_SYNT_TEST_EXE_HIST_ID) USING INDEX TWAA0011H00_PK;
COMMENT ON COLUMN TWAA0011H00.MNG_DOM_SYNT_TEST_EXE_HIST_ID IS '관리영역합성테스트실행이력ID';
COMMENT ON COLUMN TWAA0011H00.MNG_DOM_SYNT_TEST_ID IS '관리영역합성테스트ID';
COMMENT ON COLUMN TWAA0011H00.MNG_DOM_NODE_ID IS '관리영역노드ID';
COMMENT ON COLUMN TWAA0011H00.MNG_DOM_SYNT_TEST_HTTP_RSP_CODE IS '관리영역합성테스트HTTP응답코드';
COMMENT ON COLUMN TWAA0011H00.MNG_DOM_SYNT_TEST_SCS_YN IS '관리영역합성테스트성공여부';
COMMENT ON COLUMN TWAA0011H00.MNG_DOM_SYNT_TEST_RSP_MLSC IS '관리영역합성테스트응답밀리초';
COMMENT ON COLUMN TWAA0011H00.MNG_DOM_SYNT_TEST_EXE_TM IS '관리영역합성테스트실행시각';
COMMENT ON COLUMN TWAA0011H00.MNG_DOM_SYNT_TEST_INP_CNTT IS '관리영역합성테스트입력내용';
COMMENT ON COLUMN TWAA0011H00.MNG_DOM_SYNT_TEST_OPRT_CNTT IS '관리영역합성테스트출력내용';
COMMENT ON COLUMN TWAA0011H00.REG_USER_ID IS '등록사용자ID';
COMMENT ON COLUMN TWAA0011H00.REG_DDTS IS '등록상세일시TS';
COMMENT ON COLUMN TWAA0011H00.CHG_USER_ID IS '변경사용자ID';
COMMENT ON COLUMN TWAA0011H00.CHG_DDTS IS '변경상세일시TS';
COMMENT ON COLUMN TWAA0011H00.CHG_USER_IP IS '변경사용자IP';
COMMENT ON COLUMN TWAA0011H00.CHG_GBL_ID IS '변경글로벌ID';
COMMENT ON TABLE TWAA0011H00 IS 'TWAA_합성테스트실행이력';
